name: Test Front-End Code
run-name: ${{ github.actor }} is having their code tested by GitHub Actions 🚀
on:
  pull_request:
    branches: [main]
jobs:
  runner-job:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress tests
        uses: cypress-io/github-action@v2
